### PR TITLE
Add AudioBuffer, expose to DedicatedWorker

### LINKED ISSUE #111: Request to Expose AudioBuffer to DedicatedWorker
WebCodecs uses AudioBuffer as a container of unencoded audio.
https://wicg.github.io/web-codecs/#dom-audioframe-buffer

The AudioFrame, which wraps AudioBuffer, is provided as an input to AudioEncoder and as an output from AudioDecoder. We've exposed the encoder and decoder interfaces to DedicatedWorker to facilitate offloaded codec IO.

I think the change is as simple as changing the Exposed= parameter for just AudioBuffer. I'll send a PR to demonstrate.

### PR DESCRIPTION
**Pull request by chcunningham**
Closes #111

The following tasks have been completed:

 * [x] Modified Web platform tests ([link to pull request](https://chromium-review.googlesource.com/c/chromium/src/+/2611689))

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [x] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1160580)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

***
<a href="https://pr-preview.s3.amazonaws.com/chcunningham/web-audio-api-v2/pull/120.html" title="Last updated on Apr 8, 2021, 8:21 PM UTC (8ac7437)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api-v2/120/b9ee3a5...chcunningham:8ac7437.html" title="Last updated on Apr 8, 2021, 8:21 PM UTC (8ac7437)">Diff</a>

### CODE REVIEW

**Comment by rtoy** [comment]
If you rebase, I think the bikeshed issue will be gone.

**Comment by rtoy** [comment]
Looks good.  Not sure if there needs to be some text describing this or not.  The change is self-evident if you know what the original AudioBuffer looks like.

**Comment by rtoy** [comment]
Oh, if you click on the links for AudioBuffer, you're taken to the v1 spec.  And the IDL index is empty.  Not sure if that's what we want or how to solve that.  But I also don't think that's your problem to solve.

Need to talk to @tabatkins about how to do this in the proper bikeshed way.

**Comment by tabatkins** [comment]
> Oh, if you click on the links for AudioBuffer, you're taken to the v1 spec.

That's because this is a `partial interface`; it can't be the actual definition, so it links back to the only place it can find one, which is v1.

> And the IDL index is empty. 

Huh, it's not empty when I take the source and run it locally. It's not empty in the preview link either.

**Comment by padenot** [comment]
Per https://github.com/WebAudio/web-audio-api-v2/issues/111#issuecomment-846081512

**Pull request closed without merging**
